site_name: "Selfhosters.net"
site_description: "Selfhosters.net is a documentation portal for the Unraid Discord. Here you will find short guides and walkthroughs made by the  Unraid community."
site_author: "Selfhosters"
site_url: "https://selfhosters.net"

repo_name: "selfhosters/selfhosters.net"
repo_url: "https://github.com/selfhosters/selfhosters.net"
edit_uri: "https://github.com/selfhosters/selfhosters.net/edit/master/docs/"

# Configuration

# https://squidfunk.github.io/mkdocs-material/getting-started/#configuration
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: "material"
  language: "en"
  palette:
    primary: "orange"
    accent: "red"
  font:
    text: "Roboto"
    code: "Roboto Mono"
extra:
  social:
    - type: 'github'
      link: 'https://github.com/selfhosters'

# Navigation
nav:
  - Home: index.md
  - Nice to know Unraid commands: commands.md
  - Guides:
      Example 1: guides/placeholder.md
      Example 2: guides/placeholder.md
      Example 3: guides/placeholder.md
     #- Tips & Tricks/highlighting_test.md
